dual_motor_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller_dual_motor
        type: JointPositionControllerDual
    joint_name: dual_motor
    joint_speed: 0.8
    motor_master:
        id: 11
        init: 0
        min: 0
        max: 2047
    motor_slave:
        id: 21