joint_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: arm_joint
    joint_speed: 0.8
    motor:
        id: 11
        init: 0
        min: 0
        max: 2047